If youth, throughout all history, had had a champion to stand up for it; to show a doubting world that a child can think; and, possibly, do it practically; you wouldn’t constantly run across folks today who claim that “a child don’t know anything.” A child’s brain starts functioning at birth; and has, amongst its many infant convolutions, thousands of dormant atoms, into which God has put a mystic possibility for noticing an adult’s act, and figuring out its purport.

Up to about its primary school days a child thinks, naturally, only of play. But many a form of play contains disciplinary factors. “You can’t do this,” or “that puts you out,” shows a child that it must think, practically, or fail. Now, if, throughout childhood, a brain has no opposition, it is plain that it will attain a position of “status quo,” as with our ordinary animals. Man knows not why a cow, dog or lion was not born with a brain on a par with ours; why such animals cannot add, subtract, or obtain from books and schooling, that paramount position which Man holds today.

But a human brain is not in that class. Constantly throbbing and pulsating, it rapidly forms opinions; attaining an ability of its own; a fact which is startlingly shown by an occasional child "prodigy" in music or school work. And as, with our dumb animals, a child's inability convincingly to impart its thoughts to us, should not class it as ignorant.

Upon this basis I am going to show you how a bunch of bright young folks did find a champion; a man with boys and girls of his own; a man of so dominating and happy individuality that Youth is drawn to him as is a fly to a sugar bowl. It is a story about a small town. It is not a gossipy yarn; nor is it a dry, monotonous account, full of such customary "fill-ins" as "romantic moonlight casting murky shadows down a long, winding country road." Nor will it say anything about tinklings lulling distant folds; robins carolling at twilight, nor any "warm glow of lamplight" from a cabin window. No. It is an account of up-and-doing activity; a vivid portrayal of Youth as it is today; and a practical discarding of that worn-out notion that "a child don't know anything."

Now, any author, from history's dawn, always had that most important aid to writing:—an ability to call upon any word in his dictionary in building up his story. That is, our strict laws as to word construction did not block his path. But in my story that mighty obstruction will constantly stand in my path; for many an important, common word I cannot adopt, owing to its orthography.

I shall act as a sort of historian for this small town; associating with its inhabitants, and striving to acquaint you with its youths, in such a way that you can look, knowingly, upon any child, rich or poor; forward or "backward;" your own, or John Smith's, in your community. You will find many young minds aspiring to know how, and WHY such a thing is so. And, if a child shows curiosity in that way, how ridiculous it is for you to snap out:—

"Oh! Don't ask about things too old for you!"

Such a jolt to a young child's mind, craving instruction, is apt so to dull its avidity, as to hold it back in its school work. Try to look upon a child as a small, soft young body and a rapidly growing, constantly inquiring brain. It must grow to maturity slowly. Forcing a child through school by constant night study during hours in which it should run and play, can bring on insomnia; handicapping both brain and body.

Now this small town in our story had grown in just that way:—slowly; in fact, much too slowly to stand on a par with many a thousand of its kind in this big, vigorous nation of ours. It was simply stagnating; just as a small mountain brook, coming to a hollow, might stop, and sink from sight, through not having a will to find a way through that obstruction; or around it. You will run across such a dormant town, occasionally; possibly so dormant that only outright isolation by a fast-moving world, will show it its folly. If you will tour Asia, Yucatan, or parts of Africa and Italy, you will find many sad ruins of past kingdoms. Go to Indo-China and visit its gigantic Ankhor Vat; call at Damascus, Baghdad and Samarkand. What sorrowful lack of ambition many such a community shows in thus discarding such high-class construction! And I say, again, that so will Youth grow dormant, and hold this big, throbbing world back, if no champion backs it up; thus providing it with an opportunity to show its ability for looking forward, and improving unsatisfactory conditions.

So this small town of Branton Hills was lazily snoozing amidst up-and-doing towns, as Youth's Champion, John Gadsby, took hold of it; and shook its dawdling, flabby body until its inhabitants thought a tornado had struck it. Call it tornado, volcano, military onslaught, or what you will, this town found that it had a bunch of kids who had wills that would admit of no snoozing; for that is Youth, on its forward march of inquiry, thought and action.

If you stop to think of it, you will find that it is customary for our "grown-up" brain to cast off many of its functions of its youth; and to think only of what it calls "topics of maturity." Amongst such discards is many a form of happy play; many a muscular activity such as walking, running, climbing; thus totally missing that alluring "joy of living" of childhood. If you wish a vacation from financial affairs, just go out and play with Youth. Play "blind-man's buff," "hop-scotch," "ring toss," and football. Go out to a charming woodland spot on a picnic with a bright, happy, vivacious group. Sit down at a corn roast; a marshmallow toast; join in singing popular songs; drink a quart of good, rich milk; burrow into that big lunch box; and all such things as banks, stocks, and family bills, will vanish on fairy wings, into oblivion.

But this is not a claim that Man should stay always youthful. Supposing that that famous Spaniard, landing upon Florida's coral strands, had found that mythical Fountain of Youth; what a calamity for mankind! A world without maturity of thought; without man's full-grown muscular ability to construct mighty buildings, railroads and ships; a world without authors, doctors, savants, musicians; nothing but Youth! I can think of but a solitary approval of such a condition; for such a horror as war would not,—could not occur; for a child is, naturally, a small bunch of sympathy. I know that boys will "scrap;" also that "spats" will occur amongst girls; but, at such a monstrosity as killings by bombing towns, sinking ships, or mass annihilation of marching troops, childhood would stand aghast. Not a tiny bird would fall; nor would any form of gun nor facility for manufacturing it, insult that almost Holy purity of youthful thought. Anybody who knows that wracking sorrow brought upon a child by a dying puppy or cat, knows that childhood can show us that our fighting, our policy of "a tooth for a tooth," is abominably wrong.

So, now to start our story:—

Branton Hills was a small town in a rich agricultural district; and having many a possibility for growth. But, through a sort of smug satisfaction with conditions of long ago, had no thought of improving such important adjuncts as roads; putting up public buildings, nor laying out parks; in fact a dormant, slowly dying community. So satisfactory was its status that it had no form of transportation to surrounding towns but by railroad, or "old Dobbin." Now, any town thus isolating its inhabitants, will invariably find this big, busy world passing it by; glancing at it, curiously, as at an odd animal at a circus; and, you will find, caring not a whit about its condition. Naturally, a town should grow. You can look upon it as a child; which, through natural conditions, should attain manhood; and add to its surrounding thriving districts its products of farm, shop, or factory. It should show a spirit of association with surrounding towns; crawl out of its lair, and find how backward it is.

Now, in all such towns, you will find, occasionally, an individual born with that sort of brain which, knowing that his town is backward, longs to start things toward improving it; not only its living conditions, but adding an institution or two, such as any city, big or small, maintains, gratis, for its inhabitants. But so forward looking a man finds that trying to instill any such notions into a town's ruling body is about as satisfactory as butting against a brick wall. Such "Boards" as you find ruling many a small town, function from such a soporific rut that any hint of digging cash from its cast iron strong box with its big brass padlock, will fall upon minds as rigid as rock.

Branton Hills had such a man, to whom such rigidity was as annoying as a thorn in his foot. Continuous trials brought only continual thornpricks; until, finally, a brilliant plan took form as John Gadsby found Branton Hills' High School pupils waking up to Branton Hills' sloth. Gadsby continually found this bright young bunch asking:—

"Aw! Why is this town so slow? It's nothing but a dry twig!!"

"Ha!" said Gadsby; "A dry twig! That's it! Many a living, blossoming branch all around us, and this solitary dry twig, with a tag hanging from it, on which you will find: 'Branton Hills; A twig too lazy to grow!'"

Now this put a "hunch" in Gadsby's brain, causing him to say: "A High School pupil is not a child, now. Naturally a High School boy has not a man's qualifications; nor has a High School girl womanly maturity. But such kids, born in this swiftly moving day, think out many a notion which will work, but which would pass our dads and granddads in cold disdain. Just as ships pass at night. But supposing that such ships should show a light in passing; or blow a horn; or, if—if—if— By Golly! I'll do it!"

And so Gadsby sat on his blossom-bound porch on a mild Spring morning, thinking and smoking. Smoking can calm a man down; and his thoughts had so long and so constantly clung to this plan of his that a cool outlook as to its promulgation was not only important, but paramount. So, as his cigar was whirling and puffing rings aloft; and as groups of bright, happy boys and girls trod past, to school, his plan rapidly took form as follows:—

"Youth! What is it? Simply a start. A start of what? Why, of that most astounding of all human functions; thought. But man didn't start his brain working. No. All that an adult can claim is a continuation, or an amplification of thoughts, dormant in his youth. Although a child's brain can absorb instruction with an ability far surpassing that of a grown man; and, although such a young brain is bound by rigid limits, it contains a capacity for constantly craving additional facts. So, in our backward Branton Hills, I just know that I can find boys and girls who can show our old moss-back Town Hall big-wigs a thing or two. Why! On Town Hall night, just go and sit in that room and find out just how stupid and stubborn a Council, (put into Town Hall, you know, through popular ballot!), can act. Say that a road is badly worn. Shall it stay so? Up jumps Old Bill Simpkins claiming that it is a townsman's duty to fix up his wagon springs if that road is too rough for him!"

As Gadsby sat thinking thus, his plan was rapidly growing; and, in a month, was actually starting to work. How? You'll know shortly; but first, you should know this John Gadsby; a man of "around fifty;" a family man, and known throughout Branton Hills for his high standard of honor and altruism on any kind of an occasion for public good. A loyal churchman, Gadsby was a man who, though admitting that an occasional fault in our daily acts is bound to occur, had taught his two boys and a pair of girls that, though folks do slip from what Scriptural authors call that "straight and narrow path," it will not pay to risk your own Soul by slipping, just so that you can laugh at your ability in staying out of prison; for Gadsby, having grown up in Branton Hills, could point to many such man or woman. So, with such firm convictions in his mind, this upstanding man was constantly striving so to act that no complaint from man, woman or child should bring a word of disapproval. In his mind, what a man might do was that man's affair only and could stain no Soul but his own. And his altruism taught that it is not difficult to find many ways in which to bring joy to such as cannot, through physical disability, go out to look for it; and that only a small bit of joy, brought to a shut-in will carry with it such a warmth as can flow only from acts of human sympathy.

For many days Gadsby had thought of ways in which folks with a goodly bank account could aid in building up this rapidly backsliding town of Branton Hills. But, how to show that class what a contribution could do? In this town, full of capitalists and philanthropists contributing, off and on, for shipping warming pans to Zulus, Gadsby saw a solution. In whom? Why, in just that bunch of bright, happy school kids, back from many a visit to a city, and noting its ability in improving its living conditions. So Gadsby thought of thus carrying an inkling to such capitalists as to how this stagnating town could claim a big spot upon our national map, which is now shown only in small, insignificant print.

As a start, Branton Hills’ “Daily Post” would carry a long story, outlining a list of factors for improving conditions. This it did; but it will always stay as a blot upon high minds and proud blood that not a man or woman amongst such capitalists saw, in his plan, any call for dormant funds. But did that stop Gadsby? Can you stop a rising wind? Hardly! So Gadsby took into council about forty boys of his vicinity and built up an Organization of Youth. Also about as many girls who had known what it is, compulsorily to pass up many a picnic, or various forms of sport, through a lack of public park land. So this strong, vigorous combination of both youth and untiring activity, avidly took up Gadsby’s plan; for nothing so stirs up a youthful mind as an opportunity for accomplishing anything that adults cannot do. And did Gadsby know Youth? I’ll say so! His two sons and girls, now in High or Grammar school, had taught him a thing or two; principal amongst which was that all-dominating fact that, at a not too far distant day, our young folks will occupy important vocational and also political positions, and will look back upon this, our day; smiling kindly at our way of doing things. So, to say that many a Branton Hills “King of Capital” got a bit huffy as a High School stripling was proving how stubborn a rich man is if his dollars don’t aid so vast an opportunity for doing good, would put it mildly! Such downright gall by a half-grown kid to inform him; an outstanding light on Branton Hills’ tax list, that this town was sliding down hill; and would soon land in an abyss of national oblivion! And our Organization girls! How Branton Hills’ rich old widows and plump matrons did sniff in disdain as a group of High School pupils brought forth straightforward claims that cash paving a road, is doing good practical work, but, in filling up a strong box, is worth nothing to our town.

Oh, that class of nabobs! How thoroughly Gadsby did know its parsimony!! And how thoroughly did this hard-planning man know just what a constant onslaught by Youth could do. So, in about a month, his “Organization” had “waylaid,” so to say, practically half of Branton Hills’ cash kings; and had so won out, through that commonly known “pull” upon an adult by a child asking for what plainly is worthy, that his mail brought not only cash, but two rich landlords put at his disposal, tracts of land “for any form of occupancy which can, in any way, aid our town.” This land Gadsby’s Organization promptly put into growing farm products for gratis distribution to Branton Hills’ poor; and that burning craving of Youth for activity soon had it sprouting corn, squash, potato, onion and asparagus crops; and, to “doll it up a bit,” put in a patch of blossoming plants.

Naturally any man is happy at a satisfactory culmination of his plans and so, as Gadsby found that public philanthropy was but an affair of plain, ordinary approach, it did not call for much brain work to find that, possibly also, a way might turn up for putting handicraft instruction in Branton Hills’ schools; for schooling, according to him, did not consist only of books and black-boards. Hands, also should know how to construct various practical things in woodwork, plumbing, blacksmithing, masonry, and so forth; with thorough instruction in sanitation, and that most important of all youthful activity, gymnastics. For girls such a school could instruct in cooking, suit making, hat making, fancy work, art and loom-work; in fact, about any handicraft that a girl might wish to study, and which is not in our standard school curriculum. But as Gadsby thought of such a school, no way for backing it financially was in sight. Town funds naturally, should carry it along; but town funds and Town Councils do not always form what you might call synonymous words. So it was compulsory that cash should actually “drop into his lap,” via a continuation of solicitations by his now grandly functioning Organization of Youth. So, out again trod that bunch of bright, happy kids, putting forth such plain, straightforward facts as to what Manual Training would do for Branton Hills, that many saw it in that light. But you will always find a group, or individual complaining that such things would “automatically dawn” on boys and girls without any training. Old Bill Simpkins was loud in his antagonism to what was a “crazy plan to dip into our town funds just to allow boys to saw up good wood, and girls to burn up good flour, trying to cook biscuits.” Kids, according to him, should go to work in Branton Hills’ shopping district, and profit by it.

“Bah! Why not start a class to show goldfish how to waltz! I didn’t go to any such school; and what am I now? A Councilman! I can’t saw a board straight, nor fry a potato chip; but I can show you folks how to hang onto your town funds.”

Old Bill was a notorious grouch; but our Organization occasionally did find a totally varying mood. Old Lady Flanagan, with four boys in school, and a husband many days too drunk to work, was loud in approval.

“Whoops! Thot’s phwat I calls a grand thing! Worra, worra! I wish Old Man Flanagan had had sich an opporchunity. But thot ignorant old clod don’t know nuthin’ but boozin’, tobacca shmokin’ and ditch-diggin’. And you know thot our Council ain’t a-payin’ for no ditch-scoopin’ right now. So I’ll shout for thot school! For my boys can find out how to fix thot barn door our old cow laid down against.”

Ha, ha! What a circus our Organization had with such varying moods and outlooks! But, finally such a school was built; instructors brought in from surrounding towns; and Gadsby was as happy as a cat with a ball of yarn.

As Branton Hills found out what it can accomplish if it starts out with vigor and a will to win, our Organization thought of laying out a big park; furnishing an opportunity for small tots to romp and play on grassy plots; a park for all sorts of sports, picnics, and so forth; sand lots for babyhood; cozy arbors for girls who might wish to study, or talk. (You might, possibly, find a girl who can talk, you know!); also shady nooks and winding paths for old folks who might find comfort in such. Gadsby thought that a park is truly a most important adjunct to any community; for, if a growing population has no out-door spot at which its glooms, slumps and morbid thoughts can vanish upon wings of sunlight, amidst bright colorings of shrubs and sky, it may sink into a grouchy, faultfinding, squabbling group; and making such a showing for surrounding towns as to hold back any gain in population or valuation. Gadsby had a goodly plot of land in a grand location for a park and sold it to Branton Hills for a dollar; that stingy Council to lay it out according to his plans. And how his Organization did applaud him for this, his first “solo work!”

But schools and parks do not fulfill all of a town’s calls. Many minds of varying kinds will long for an opportunity for finding out things not ordinarily taught in school. So Branton Hills’ Public Library was found too small. As it was now in a small back room in our High School, it should occupy its own building; down town, and handy for all; and with additional thousands of books and maps. Now, if you think Gadsby and his youthful assistants stood aghast at such a gigantic proposition, you just don’t know Youth, as it is today. But to whom could Youth look for so big an outlay as a library building would cost? Books also cost; librarians and janitors draw pay. So, with light, warmth, and all-round comforts, it was a task to stump a full-grown politician; to say nothing of a plain, ordinary townsman and a bunch of kids. So Gadsby thought of taking two bright boys and two smart girls to Washington, to call upon a man in a high position, who had got it through Branton Hills’ popular ballot. Now, any politician is a convincing orator. (That is, you know, all that politics consists of!); and this big man, in contact with a visiting capitalist, looking for a handout for his own district, got a donation of a thousand dollars. But that wouldn’t start a public library; to say nothing of maintaining it. So, back in Branton Hills, again, our Organization was out, as usual, on its war-path.

Branton Hills’ philanthropy was now showing signs of monotony; so our Organization had to work its linguistic ability and captivating tricks full blast, until that thousand dollars had so grown that a library was built upon a vacant lot which had grown nothing but grass; and only a poor quality of it, at that; and many a child and adult quickly found ways of profitably passing odd hours.

Naturally Old Bill Simpkins was snooping around, sniffing and snorting at any signs of making Branton Hills “look cityish,” (a word originating in Bill’s vocabulary.)

“Huh!! I didn’t put in any foolish hours with books in my happy childhood in this good old town! But I got along all right; and am now having my say in its Town Hall doings. Books!! Pooh! Maps! BAH!! It’s silly to squat in a hot room squinting at a lot of print! If you want to know about a thing, go to work in a shop or factory of that kind, and find out about it first-hand.”

“But, Bill,” said Gadsby, “shops want a man who knows what to do without having to stop to train him.”

“Oh, that’s all bosh! If a boss shows a man what a tool is for; and if that man is any good, at all, why bring up this stuff you call training? That man grabs a tool, works ’til noon; knocks off for an hour; works ’til——”

At this point in Bill’s blow-up an Italian Councilman was passing, and put in his oar, with:—

“Ha, Bill! You thinka your man can worka all right, firsta day, huh? You talka crazy so much as a fool! I laugha tinkin’ of you startin’ on a patcha for my boota! You lasta just a half hour. Thisa library all righta. This town too mucha what I call tight-wad!”

Oh, hum!! It’s a tough job making old dogs do tricks. But our Organization was now holding almost daily sittings, and soon a bright girl thought of having band music in that now popular park. And what do you think that stingy Council did? It actually built a most fantastic band-stand; got a contract with a first-class band, and all without so much as a Councilman fainting away!! So, finally, on a hot July Sunday, two solid hours of grand harmony brought joy to many a poor Soul who had not for many a day, known that balm of comfort which can “air out our brains’ dusty corridors,” and bring such happy thrills, as Music, that charming Fairy, which knows no human words, can bring. Around that gaudy band-stand, at two-thirty on that first Sunday, sat or stood as happy a throng of old and young as any man could wish for; and Gadsby and his “gang” got hand-clasps and hand-claps, from all. A good band, you know, not only can stir and thrill you; for it can play a soft crooning lullaby, a lilting waltz or polka; or, with its wood winds, bring forth old songs of our childhood, ballads of courting days, or hymns and carols of Christmas; and can suit all sorts of folks, in all sorts of moods; for a Spaniard, Dutchman or Russian can find similar joy with a man from Italy, Norway or far away Brazil.
Now I’ll drop civic affairs for a bit, and go on to a most natural act in this city of many young chaps and charming young girls which was slowly working up all through this history, as Mayor Gadsby had occasion to find out, sitting comfortably on his porch on a hot, sultry August night. Amidst blossoming shrubs, a dim form slowly trod up his winding pathway. It was a young man, plainly trying to act calmly, but couldn’t. It was Frank Morgan, our radio broadcasting “boss”, you know, who, for many a month, had shown what a romantic public calls “a crush” for Gadsby’s young Nancy.

So a jolly call of:—“What’s on your mind, boy?” rang out, as Frank sank wiltingly into a hammock, wiping his brow of what I actually know was not natural humidity from an August night! Now Gadsby, who was, as I said, a gay Lothario in his own youth, saw right off what was coming, and sat back, waiting. Finally, finishing a bad attack of coughing, (though Frank hadn’t any cold!), that young man said:—

“I,—that is, Nancy and I,—or, I will say that I want to,—that is,—I think Nancy and I would—” and Gadsby took pity on him, right off.

Nancy had always had a strong liking for Frank. Both had grown up in Branton Hills from babyhood; and Gadsby thought back about that lassoo which had brought him Lady Gadsby. Now asking a girl’s Dad for that young lady’s hand is no snap for any young swain; and Gadsby was just that kind of a Dad who would smooth out any bumps or rough spots in such a young swain’s path. Nancy wasn’t a child, now, but a grown-up young woman; so Gadsby said:—

“Frank, Lady Gadsby and I know all about how much you think of Nancy; and what Nancy thinks of you. So, if you want to marry, our full wish is for a long and happy union. Nancy is out in that arbor, down this back path; and I’ll watch that nobody disturbs you two for an hour.”

At this grand turn of affairs, Frank could only gasp:—“OH-H-H!!” and a shadowy form shot down that dusky path; and from that moonlit arbor, anybody knowing how a man chirps to a canary bird, would know that two young birds put a binding approval upon what His Honor had just said!!

Many a man has known that startling instant in which Dan Cupid, that busy young rascal, took things in hand, and told him that his baby girl was not a baby girl now, and was about to fly away from him. It is both a happy and a sad thrill that shoots through a man at such an instant. Happy and joyous at his girl’s arrival at maturity; sad, as it brings to mind that awkward fact that his own youth is now but a myth; and that his scalp is showing vacant spots. His baby girl in a bridal gown! His baby girl a Matron! His baby girl proudly placing a grandchild in his lap!! It’s an impossibility!! But this big world is full of this kind of impossibility, and will stay so as long as Man lasts.

So Nancy, tiny, happy, laughing Nancy, was “found” through a conspiracy by Dan Cupid and Frank Morgan; and right in all glory of youth. Youth!! Ah, what a word!! And how transitory! But, how grand! as long as it lasts. How many millions in gold would pour out for an ability to call it all back, as with our musical myth, Faust. During that magic part of a child’s growth this world is just a gigantic inquiry box, containing many a topic for which a solution is paramount to a growing mind. And to whom can a child look, but us adults? Any man who “can’t stop now” to talk with a child upon a topic which, to him is “too silly for anything,” should look back to that day upon which that topic was dark and dubious in his own brain. A child who asks nothing will know nothing. That is why that “bump of inquiry” was put on top of our skulls.
But to go back to Nancy. It was in August that Frank had stumblingly told Gadsby of his troth; and so, along in April, Branton Hills was told that a grand church ritual would occur in May. May, with its blossoms, birds and balmy air! An idyllic month for matrimony. I wish that I could call this grand church affair by its common, customary nomination; but that word can’t possibly crowd into this story. It must pass simply as a church ritual.

All right; so far, so good. So, along into April all Branton Hills was agog, awaiting information as to that actual day; or, I should say, night.

Gadsby’s old Organization of Youth was still as loyal to all in it as it was, way back in days of its formation; days of almost constantly running around town, soliciting funds for many a good Municipal activity. Finally this group got cards announcing that on May Fourth, Branton Hills’ First Church would admit all who might wish to aid in starting Nancy and Frank upon that glamorous path to matrimonial bliss.

May Fourth was punctual in arriving; though many a young girl got into that flighty condition in which a month drags along as though in irons, and clock-hands look as if stuck fast. But to many girls, also, May Fourth was not any too far away; for charming gowns and dainty hats do not grow upon shrubs, you know; and girls who work all day must hurry at night, at manipulating a thousand or so things which go towards adorning our girls of today.

Now, an approach to a young girl’s “big day” is not always as that girl might wish. Small things bob up, which, at first, look actually disastrous for a joyous occasion; and for Nancy and Frank, just such a thing did bob up; for, on May Third, a pouring rain and whistling wind put Branton Hills’ spirits way, way down into a sorrowful slump. Black, ugly, rumbling clouds hung aggravatingly about in a saturation of mist, rain and fog; and roads and lawns got such a washing that Nancy said:—

“Anyway, if I can’t walk across that front church yard, I can swim it!!”

That was Nancy; a small bunch of inborn good humor; and I’ll say, right now, that it took good humor, and lots of it, to look upon conditions out of your control, with such outstanding pluck!

But young Dan Cupid was still around, and got in touch with that tyrannical mythological god who controls storms; and put forth such a convincing account of all Nancy’s good points, (and Frank’s too, if anybody should ask you) that a command rang out across a stormy sky:—

“Calling all clouds!! Calling all clouds!! All rain to stop at midnight of May Third! Bright Sun on May Fourth, and no wind!”

So, as Nancy took an anxious squint out of doors at about six o’clock on that important morning, (and what young girl could go on, calmly snoozing on such a day?) Lo!! Old Sol was smiling brightly down on Branton Hills; birds sang; all sorts of blossoming things had had a good drink; and a most glorious sky, rid of all ugly clouds, put our young lady into such a happy mood that it took a lot of control to avoid just a tiny bit of humidity around a small pair of rich, brown orbs which always had that vibrating, dancing light of happy youth; that miraculous “joy of living.”

And, what a circus was soon going full tilt in Mayor Gadsby’s mansion! If that happy man so much as said:—“Now, I——” a grand, womanly chorus told him that “a man don’t know anything about such affairs;” and that a most satisfactory spot for him was in a hammock on his porch, with a good cigar! That’s it! A man is nominally monarch in his own family; but only so on that outstanding day upon which a bridal gown is laid out in all its glory on his parlor sofa, and a small mob of girls, and occasionally a woman or two, is rushing in and out, up and down stairs, and finding as much to do as a commonly known microscopic “bug” of prodigious hopping ability finds at a dog show. Rush! rush! rush! A thousand thoughts and a million words, (this crowd was all girls, you know!) making that parlor as noisy as a saw mill! But Gadsby laughingly staid out of it all, watching big armfuls of bloom and many a curious looking box go in through that front door; flying hands rapidly untying glorious ribbon wrappings.

Now, upon all such occasions you will find, if you snoop around in dining room or pantry, an astonishing loaf of culinary art, all fancy frosting, and chuck full of raisins and citron, which is always cut upon such an auspicious occasion; and it is as hard to avoid naming it, in this story, as it is to withstand its assault upon your stomach.

Oh hum! Now what? Aha! May Fourth, lasting, as Nancy said, “for about a million months,” finally got Gadsby’s dining room clock around to six-fifty; only about an hour, now, to that grand march past practically half of Branton Hills’ population; for all who couldn’t jam into that commodious church would stand around in a solid phalanx, blocking all traffic in that part of town; for all Branton Hills was fond of its Mayor’s “baby girl.”

But, during this rush and hubbub, how about Frank? Poor boy! Now, if you think that a young lad at such an instant is as calm as a millpond, you don’t know romantic Youth, that’s all. About forty of Gadsby’s old Organization boys, now many young chaps, had bought him a car, which Nancy was not to know anything about until that throwing of old boots, and what is also customary, had quit. Frank didn’t want to hold it back from Nancy, but what can a chap do, against forty? Also, last night, at a big “so sorry, old chap” party, Frank had found how loyal a bunch of old pals can turn out; and this “grand launching into matrimonial doubt” had put him in a happy mood for that all important oration of two words:—“I do.”

So now I’ll hurry around to church to find out how Nancy’s Organization girls put in a long day of hard labor; not only at floor work, but up on stools and chairs. My! My! Just look and gasp!! A long chain of lilacs runs from door to altar in two rows. And look at that big arch of wistaria and narcissus half way along! Artificial palms stand in curving ranks from organ to walls; and, with all lights softly glowing through pink silk hoods; and with gilt cords outlining an altar-dais of moss and sprays of asparagus, it is a sight to bring a thrill to anybody, young or old.

And, now—aha!! With organist and Pastor waiting, a murmur and hand-clapping from that big front door told all who had luckily got in that Nancy was coming! It took thirty cars to bring that bridal party to church; for not a boy or girl of our old Organization would miss this occasion for a farm, with a pig on it with four kinks in its tail. Now, naturally, any girl would long to walk up that Holy path with Nancy, but too many would spoil things; so, by drawing lots, Nancy had for company, Sarah Young, Lucy Donaldson, Priscilla Standish, Virginia Adams, Doris Johnson and Cora Grant; with Kathlyn as Maid of Honor, as charming an array of youthful glory as you could find in all Branton Hills.

Until this important arrival, Branton Hills’ famous organist, just plain John Smith, was playing softly,—“Just a Song at Twilight,” watching for a signal from Mayor Gadsby; and soon swung into that famous march which brought forth a grand thrill, as tiny, blushing, palpitating Nancy took “Dad’s” arm, gazing with shining orbs at that distant—oh, so distant—altar.

Now I want to know why anybody should want to cry on such a grand occasion. What is sad about it? But many a lash was moist as that tiny vision of glamorous purity slowly trod that fragrant pathway. Possibly girls can’t avoid it; anyway, our Branton Hills girls didn’t try to do so.

Gadsby, as has many a good old Dad, fought back any such showing; but I won’t say that his thoughts didn’t nag him; for, giving away your baby girl to any young, though first-class chap, is not actually fun. But that long, long trail finally brought him to that mossy dais, at which Frank, coming in through a handy door, stood waiting. Nancy was as calm as a wax doll; but Frank stood shaking with a most annoying cough (of imaginary origin!) as Pastor Brown stood, book in hand. Now I won’t go through with all that was said; nor say anything about Nancy’s tiny, warm, soft hand as it was put in Frank’s big clumsy fist by Pastor Brown. Nor about that first Holy kiss; nor that long, mighty roar of organ music, as our happy, blushing pair trod that long pathway, doorwards. You know all about it, anyway, as most such rituals follow a standard custom. Nor shall I go into that happy hour at His Honor’s mansion, during which that fancy loaf of frosting, raisins and citron was cut; (and which many a girl put in a pillow that night!); nor of that big bridal bunch of blossoms, which was thrown from a stairway into a happy group of hopping, jumping, laughing girls. (But I will say,—shhhh! that Kathlyn caught it!); nor anything of Nancy and Frank’s thrilling trip to Branton Hills’ big railway station, in that gift car which Nancy thought was a king’s chariot; nor of a grand, low bow by old Pat Ryan of that station’s trunk room. It was just that customary “All aboard!!” a crowd’s “Hooray!!” and “Good Luck!!”, with Branton Hills’ Municipal Band a-blaring, and a mighty mob shouting and waving.
Oh, hum! I’ll turn from this happy affair now and try to find out what was going on in this thriving, hustling city. Now you probably think of a city as a gigantic thing; for, if you go up onto a high hill, and look around across that vast array of buildings, parks, roads and distant suburbs, you not only think that it is a gigantic thing, you know it is. But, is it?

Just stop and think a bit. All such things as bulk, or width, you know by comparison only; comparison with familiar things. So, just for fun, go up in an imaginary balloon, about half way to that old Moon, which has hung aloft from your birth—(and possibly a day or two in addition)—and look down upon your “gigantic” city. How will it look? It is a small patch of various colors; but you know that, within that tiny patch, many thousands of your kind hurry back and forth; railway trains crawl out to far-away districts; and, if you can pick out a grain of dust that stands out dimly in a glow of sunlight, you may know that it is your mansion, your cabin or your hut, according to your financial status. Now, if that hardly shows up, how about you? What kind of a dot would you form in comparison? You must admit that your past thoughts as to your own pomposity will shrink just a bit! All this shows us that could this big World think, it wouldn’t know that such a thing as Man was on it. And Man thinks that his part in all this unthinkably vast Cosmos is important! Why, you poor shrimp! if this old World wants to twitch just a bit and knock down a city or two, or split up a group of mountains, Man, with all his brain capacity, can only clash wildly about, dodging falling bricks. No. You wouldn’t show up from that balloon as plainly as an ant, in crawling around our Capitol building at Washington.

But why all this talk about our own inconspicuosity? It is simply brought up to accompany Nancy’s thoughts as that train shot across country; for Nancy, until now, had not known anything approaching such a trip. So this happy, happy trip, back upon which many a woman looks, with a romantic thrill, was astounding to such a girl. From Branton Hills to San Francisco; a boat to Honolulu, Manila, Shanghai, Hong Kong, Colombo, and finally Cairo. Ah! Cairo!! In thinking of it you naturally bring up two words—“Pyramids” and “Sphinx”, words familiar from school days. Practically from birth, Nancy, along with millions of folks, had known that famous illustration of a thing half lion and half woman; and a mountainous mass of masonry, built for a king’s tomb. So, standing right in front of both, Nancy and Frank got that wondrous thrill coming from attaining a long, long wish. From Cairo to Italy, Spain, London, Paris, and that grand Atlantic sail, landing at Boston, and hustling by fast train (but how slow it did go!!) to Branton Hills! So, along about Thanksgiving Day, about half of its population was again at its big railway station, for Nancy was coming back. (And Frank, too, if anybody should ask you.)

And with that big Municipal Band a-booming and blaring, and a crowd of our old Organization girls pushing forward, did Branton Hills look good to Nancy? And did Nancy look good to Branton Hills? What a glorious tan, from days and days on shipboard! And was that old Atlantic ugly? Ask Frank, poor chap, who, as on that big Pacific, had found out just what a ship’s rail is for! And that stomachs can turn most amazing flip-flops if an old boat is too frisky!

In just an instant, actual count, Nancy was in Lady Gadsby’s arms, fighting valiantly to hold back a flood of big, happy sobs; and Frank was busy, grabbing a cloud of hands surging towards him.

Coming back from a long trip is a happy occasion. And it is also mighty good to put a trunk or a bag down, knowing that it will “stay put” for a day or two, anyway. That constant packing and unpacking on a long trip, soon turns into an automatic function; and how Nancy did worry about what transportation customs in various lands would do to a first class trunk which has a romantic history, owing to its coming as a matrimonial gift from a group of loving girls. But now; ah!! Put it away, and your things around, in familiar disposal.

Long trips do bring lots of fun and information; but a truly long trip is tiring, both in body and mind.

But Nancy and Frank won’t stay with Gadsby long; for, during that trip, a charming bungalow was built on a lot of Gadsby’s, facing City Park; and Nancy put in many days arranging things in it. Anybody who has had such joyful work to do, knows how assiduously a young pair would go about it; for two young robins carrying bits of cotton and string up to a criss-cross of twigs in a big oak, with constant soft, loving chirps, “had nothing,” according to our popular slang, on Nancy and Frank.

Finally “moving in day” got around, with that customary party, to which you carry a gift to add to such things as a young husband on only a small salary can install. And how gifts did pour in!! Rugs, chairs, small stands, urns, clocks, photos in wall mountings, dainty scarfs (all handwork by our girls in our Night School), books, lamps, a “radio” from Station KBH, until, finally, a big truck found an opportunity in that coming and going throng to back in and unload an upright piano, all satin ribbon wrappings, with a card:—“From Branton Hills’ Municipal Band.”
I could go on for hours about this starting out of Nancy and Frank, but many civic affairs await us; for Julius Gadsby, who has not got into this story up to now, had, from his constant poring through all kinds of books of information, built up a thorough insight into fossils; and you know that Kathlyn is way up in Biology; which brings in our awkward “bugs” again. Now bugs will burrow in soil, and always did, from History’s birth; building catacombs which at last vanish through a piling up of rocks, sand or soil on that spot. Now Julius continually ran across accounts of important “finds” of such fossils, and with Kathlyn’s aid was soon inaugurating popular clamor for a big Hall of Natural History.

This, Julius and Kathlyn thought, would turn out as popular, in a way, as living animals out at our Zoo. But an appropriation for a Hall of Natural History is a hard thing to jam through a City Council; for though its occupants call for no food, you can’t maintain such a building without human custody; “which,” said Old Bill Simpkins, “is but a tricky way of saying CASH!!” But our Council was by now so familiar with calls from that famous “Organization”, and, owing to its inborn faith in that grand body of hustling Youth, such a building was built; Julius and Kathlyn arranging all displays of fossil birds, plants, “bugs,” footprints, raindrop marks, worms, skulls, parts of jaws, and so on. And what a crowd was on hand for that first public day! Julius and Kathlyn took visitors through various rooms, giving much data upon what was shown; and many a Branton Hills inhabitant found out a lot of facts about our vast past; about organisms living so far back in oblivion as to balk Man’s brain to grasp. Kathlyn stood amongst groups of botanical fossilizations, with Gadsby not far away, as this studious young woman told school pupils how our common plants of today through various transitions in form, show a kinship with what now lay, in miraculously good condition, in this big Hall; and Julius told staring groups how this or that fossil did actually link such animals as our cow or walrus of today with original forms totally apart, both in looks and habits. And it was comforting to Gadsby to find pupils asking how long ago this was, and noting that amazing look as Julius had to say that nobody knows.

Such a building is an addition to any city; for this big World is so old that human calculation cannot fathom it; and it will, in all probability, go on always. So it is improving a child’s mind to visit such displays; for it will start a train of thoughts along a path not commonly sought if such institutions do not stand as attractions. Now, in any community a crank will bob up, who will, with loud acclaim and high-sounding words, avow that it “is a scandalous drain on public funds to put up such a building just to show a lot of rocks, animals’ ribs and birds’ skulls.” But such loud bombasts only show up an “orator’s” brain capacity (or lack of it), and actually bring studious folks to ask for just such data upon things which his ridiculing had run down. It is an old, old story, that if you want a city’s population to go in strongly for anything, and you start a loud, bawling campaign against it, that public will turn to it for information as to its worth. So, just such a loud, bawling moron had to drift into our Hall on its inauguration day, and soon ran smack up against Kathlyn! That worthy girl, allowing him to “blow off” a bit, finally said:—

“I know you. You run a stock farm. All right. You want to know all you can about matching and crossing your stock, don’t you? I thought so. But God did all that, long, oh, so long ago; gradually producing such animals as you own today; and all you can do is to follow along, in your puny way, and try to avoid a poor quality of stock mixing with yours. This building contains thousands of God’s first works. It won’t do you a bit of harm to look through our rooms. Nothing will jump out at you!”

At that that barking critic shut up! And Gadsby slid outdoors, chuckling:—

“That’s my girl talking!! That’s my Kathlyn!!”

It is curious why anybody should pooh-pooh a study of fossils or various forms of rocks or lava. Such things grant us our only vision into Natural History’s big book; and it isn’t a book in first-class condition. Far from it! Just a tiny scrap; a slip; or, possibly a big chunk is found, with nothing notifying us as to how it got to that particular point, nor how long ago. Man can only look at it, lift it, rap it, cut into it, and squint at it through a magnifying glass. And,—think about it. That’s all; until a formal study brings accompanying thoughts from many minds; and, by such tactics, judging that in all probability such and such a rock or fossil footprint is about so old. Natural History holds you in its grasp through just this impossibility of finding actual facts; for it is thus causing you to think. Now, thinking is not only a voluntary function; it is an acquisition; an art. Plants do not think. Animals probably do, but in a primary way, such as an aid in knowing poisonous foods, and how to bring up an offspring with similar ability. But Man can, and should think, and think hard and constantly. It is ridiculous to rush blindly into an action without looking forward to lay out a plan. Such an unthinking custom is almost a panic, and panic is but a mild form of insanity.

So Kathlyn and Julius did a grand, good thing in having this Hall as an addition to Branton Hills’ institutions.

Now, in any city or town, or almost any small community, you will find a building, or possibly only a room, about which said city or town has nothing to say. It is that most important institution in which you put a stamp on your mail and drop it into a slot, knowing that it will find its way across city or country to that man or woman who is waiting for it.

But how many young folks know how this mail is put out so quickly, and with such guaranty against loss? Not many, I think, if you ask. So Gadsby, holding up Youth as a Nation’s most important function in its coming history, thought that any act which would instruct a child in any way, was worthy. So, on a Saturday morning His Honor took a group of Grammar School pupils to a balcony in back of that all-hiding partition, and a postal official, showing all mail handling acts individually, said:—

“In this country, two things stand first in rank: your flag and your mail. You all know what honor you pay to your flag, but you should know, also, that your mail,—just that ordinary postal card—is also important. But a postal card, or any form of mail, is not important, in that way, until you drop it through a slot in this building, and with a stamp on it, or into a mail box outdoors. Up to that instant it is but a common card, which anybody can pick up and carry off without committing a criminal act. But as soon as it is in back of this partition, or in a mail box, a magical transformation occurs; and anybody who now should willfully purloin it, or obstruct its trip in any way, will find prison doors awaiting him. What a frail thing ordinary mail is! A baby could rip it apart, but no adult is so foolish as to do it. That small stamp which you stick on it, is, you might say, a postal official, going right along with it, having it always in his sight.”

A giggling girl was curious to know if that was why a man’s photo is on it.

“Possibly,” said our official, laughing. “But wait a bit. Look downstairs. As your mail falls in through that slot, or is brought in by a mailman, it is put through an ink-daubing apparatus—that’s it, right down in front of you—which totally ruins its stamp. How about your man’s photo, now?”

A good laugh rang around, and our official said:—

“Now a man sorts it according to its inscription, puts it into a canvas bag and aboard a train, or possibly an aircraft. But that bag has mail going to points a long way apart, so a man in a mail car sorts it out, so that Chicago won’t find mail in its bag which should go to California.”

At this point our giggling girl said:—

“Ooooo! I had a Christmas card for Missouri go way down to Mississippi!”

“How did you mark it?”

“I put M-i-s-s for Missouri.”

“Try M-o, and I wish you luck.”

As that laugh ran round, our official said:—

“Now you know that you can buy a long, narrow stamp which will hurry your mail along. So, as all mail in this building is put up in many a small bunch, all with such stamps attract a mailman, who will so wrap a bunch that that kind of a stamp will show up plainly. Upon its arrival at a distant point, a boy will grab it, and hurry it to its final goal. But that stamp will not hurry it as long as it is on that train.”

Our giggling girl, swinging in again, said:—

“What? With that stamp right on top?”

“How can it?” said our official. “A train can only go just so fast, stamp or no stamp.”

“Oh.”

Our boys and girls got a big thrill from this visit in back of that partition, and told Gadsby so. On coming out of that building our party saw a big patrolman putting a small boy into a patrol wagon. That poor kid was but a bunch of rags, dirty, and in a fighting mood. Our boys got a big laugh out of it. Our girls, though, did not. Young Marian Hopkins who had that fairy wand, you know, at our airport inauguration, said:—

“Oh, that poor child! Will that cop put him in jail, Mayor Gadsby?” At which His Honor instantly thought of a plan long in his mind. Branton Hills had a court room, a child’s court, in fact, at which a kindly man looks out for just such young waifs—trying to find out why such tots commit unlawful acts. So Gadsby said:—

“I don’t know, Marian, but I want you young folks to go on a visit, tonight, to our night court, to find out about just such wild boys. How many want to go?”

To his satisfaction, all did; and so, that night that court room had rows of young folks, all agog with curiosity which a first visit to a court stirs up in a child. Just by luck, our young vagrant in rags was brought in first, shaking with childish doubt as to what was going to occur. But that kindly man sitting back of that big mahogany railing had no thought of scaring a child, and said, calmly:—

“Now, boy, what did you do that you ought not to do; and why did you do it?”

As our boys sat nudging and winking, but with our girls growing sad from sympathy, our young culprit said:—

“Aw! I grabs a bun, and dis big cop grabs my collar!”

“But why did you grab that bun? It wasn’t yours, you know.”

“Gosh, man!! I was hungry!!”

“Hungry? Don’t your folks look out for you?”

“Naw; I do my own looking. And that’s what I was doing, too!”

“What had you for food all day?”

“Just that bun. And say!! I only got half of it! That big cop was so rough!”

“Did that cop, as you call him, hurt you?”

“Hurt!! I should say not!! I put up a good stiff scrap! I paid him back, blow for blow! No big gas-bag of a cop is going to wallop this kid and not pay for it!”

“But, boy, don’t your folks bring you up to know that it is wrong to rob anybody?”

“Naw! My Dad robs folks, and just got six months for it. So why shouldn’t I? It’s all right to do what your Dad will do, isn’t it?”

“Not always, boy,” and our girls in row two and our boys in row four sat sad and glum at this portrayal of youthful sin. Finally that big kindly man, thoughtfully rubbing his chin, said:—

“Whom did your Dad rob?”

“I dunno. It was a Ford car. Nobody wasn’t in it, so why not grab it? That’s what Dad said. You can pick up a bit of cash for a car, you know, boss. And say, if a car brung only six months, how long will I squat in jail for swiping this half bun? Aw! Go slow, boss! I ain’t no bad kid! Only just a hungry mutt. Gosh!! How I wish I had a glass of milk!”

From row two a young, vigorous girlish form shot out, dashing for a doorway; and as that big kindly man was still rubbing his chin, Marian burst in again, rushing, sobbingly, to that sad bunch of rags, holding out a pint of milk and two hot biscuits. A quick snatch by two horribly dirty young hands, a limp flop on a mat at that big mahogany railing, and a truly hungry child was oblivious to all around him. And I’ll say that our boys, in row four, had lumpy throats. But finally that big kindly man said:—

“Though taking things unlawfully is wrong, conditions can occur in which so young a culprit is not at fault. This young chap has had no bringing up, but has run wild. A child will not know right from wrong if not taught; and, as it is a primary animal instinct to obtain food in any way, I will simply put this boy in a school which Branton Hills maintains for just such youths.”

At this both row two and row four burst out in such a storm of hand-clapping that Gadsby found that this visit had shown his young folks, from actual contact with a child without training, how important child-raising is; and how proud a city is of such as act according to law.
In almost any big town, around Autumn, you will annually run across that famous agricultural show known as a County Fair; and, as Branton Hills had a big park, which you know all about, right in front of Nancy’s and Frank’s small bungalow, it was a most natural spot for holding it. And so, as this happy pair’s third Autumn got around, stirring activity in that big park also got a-going; for railings for stockyards don’t grow all built; yards and yards of brown canvas don’t just blow into a park; nor do “hot dog” and popcorn stands jump up from nothing. And Nancy, rocking on that bungalow porch, could watch all this work going on. And rocking was about all that Nancy could, or, I should say, should do, just now.

What a sight it was! Trucks; small cars; wagons; a gang with a tractor plowing up hard spots; a gang picking up rocks, grading humpy spots, and laying out ground plans. Masons building walls, and all kinds of goods arriving, by tons. But out of all that confusion and ado a canvas town will grow, strung from top to bottom with gaily flapping flags and hanging bunting, and that customary “mid-way” with its long rows of gaudy billboards, in front of which circus ballyhoo artists will continuously bawl and shout out claims about sword-swallowing, tattooing, hula-hula dancing, boa constrictor charming, or a Punch and Judy show.

At a County Fair two things stand out as most important: farm stock and that oval track around which swiftly trotting colts will thrill thousands; and, I’ll say, shrink a bank account or two! But, of all sights, I don’t know of any with such drawing ability for kids as just such a carnival lot. So, daily, as soon as school was out, throngs of happy, shouting, hopping, jumping boys and girls would dash for that big park; looking, pointing, and climbing up on auto tops, into lofty oaks, onto tall rocks, or a pal’s back; for if anything is difficult for a boy to obtain a sight of, nothing in climbing that an orang-outang can do, will balk him!

So Nancy sat calmly rocking, rocking, rocking, and,—but, pardon! I’ll go on with this story. All I know is that Frank, arriving from work at Radio Station KBH, wouldn’t so much as look at that big carnival lot, but would rush in, in a most loving, solicitous way which always brought a kiss and a blush from Nancy. Now if I don’t quit talking about this young pair you won’t know anything about that big show going up in front of that happy bungalow. Almost daily Lady Gadsby would drop in on Nancy, bringing all sorts of dainty foods; and His Honor, with Kathlyn, Julius and Bill, paid customary visits.

“But that fair!” you say. “How about that fair?”

Ah! It was a fair, I’ll say! What mobs on that first day! And what a din!! Bands playing, ballyhoos shouting, popcorn a-popping, “hot dogs” a-sizzling, ducks squawking, cows lowing, pigs grunting, an occasional baby squalling; and ’midst it all, a choking cloud of dust, a hot Autumn wind, panting, fanning matrons, cussing husbands; all working toward that big oval track at which all had a flimsy possibility of winning a million or two (or a dollar or two!). Oh, you County Fairs! You bloom in your canvas glory, annually. You draw vast crowds; you show high quality farm stock, gigantic pumpkins, thousands of poultry, including our “Thanksgiving National Bird”. You fill coops with fancy squabs, fat rabbits, and day-old chicks. You show many forms of incubators, churns, farming apparatus, pumps, plows, lighting plants for small farms, windmills, “bug” poisons, and poultry foods. And you always add a big balloon, which you anchor, so that kids may soar aloft until a windlass pulls it down. You fill us with food that would kill a wild goat, but you still last! And may you always do so; for, within your flapping, bulging canvas walls, city man rubs against town man, rich and poor girls bump, snobs attain no right of way, and a proud, happy boy or girl shows a “First Class” satin ribbon which a lovingly brought-up calf or poultry brood has won.

Only a satin ribbon, but, displaying it to a group of admiring young pals brings to a child that natural thrill from accomplishing anything worthy of public acclaim. Such thrills will not crowd in as Maturity supplants Youth; and so I say, “a trio of our customary huzzas” for any child who can carry away a satin ribbon from a County Fair.

But what about our good Mayor during all this circus hullabaloo? Did important thoughts for still improving Branton Hills pass through his busy mind? Not just now; but fond, anxious thoughts did; for his mind was constantly on Nancy; tiny, darling Nancy, his baby girl. For, during that noisy carnival, folks saw (or thought so, you know), a big bird with long shanks and a monstrous bill, circling round and round that small bungalow’s roof, plainly looking for a spot to land on. Lady Gadsby and old Doctor Wilkins saw it, too, and told Nancy that that big hospital which our old Organization had built, was holding a room for instant occupancy; and, as that big bird daily swung down, down, down, almost grazing that small roof, Frank, poor chap, as shaky as at his church ritual, thirty months ago, staid away from Radio Station KBH, and stuck to that small bungalow as a fly sticks around a sugar bowl.

Finally, on a crisp Autumn night, that soaring bird shot straight down with such an assuring swoop, that old Doc Wilkins, indoors with Nancy, saw it and said, quickly:—

“On your way, Nancy girl!!” and that part of Branton Hills saw his car racing hospitalwards, with Lady Gadsby fondly patting Nancy’s tiny, cold hands, and saying just such loving things as a woman would, naturally, to a young girl on such a trip. But Gadsby and Frank? Ah! Poor, half-crazy things! No car would do at all! No, sir!! A car was far too slow! And so, across lots, down into many a man’s yard, and jumping high walls, shot two shadowy forms, arriving at that big hospital, badly blown, just as Lady Gadsby and old Doc Wilkins took Nancy’s arms, and got slowly to that big door with its waiting rolling chair.

Now this stork’s visit is nothing out of ordinary in World affairs. Millions and billions of visits has it, and its kind, flown—to king’s mansion or a black Zulu woman’s hut. But this flight was poor Frank’s initiation to that awful hour of blank panic, during which a young husband is boiling hot or icy cold in turn. God!! How still a hospital corridor is!! How doctors and assistants do float past without as much sound as falling snow! Oh! How long Frank and His Honor sat, stood, or trod up and down, watching that room door!! What was going on? Was Nancy all right? Oh!! Why this prolonging of agonizing inactivity? Can’t anybody say anything? Isn’t anybody around, at all? But hospital doctors and nursing staffs, though pitying a young chap, must pass him up for that tiny lady, who now was but a tool in God’s hands; in God’s magic laboratory. And so—— Ah!! Doctor Wilkins is coming—and smiling!!

“A baby girl—and with a ripping good pair of lungs!” but has to jump quick to catch Frank, who has sunk in a swoon. And Mayor Gadsby’s collar is as limp as a dish-rag!

Ah! Man, man, man! and woman, woman, woman! Just you two! God’s only parts in His mighty plan for living actuality. Not only with Man and animals, but also down,—way, way down amongst plants. Just two parts. Only two!! And Baby, you tiny bunch of wriggling, gurgling humanity, by that slowly ticking clock is your turn in this mighty World, unavoidably arriving. Mama, Papa, and all of us will go on, for a bit, growing old and gray, but you, now so young and frail, will stand sturdily, and willingly, in our vacancy; and carry on God’s will!
As this is a history of a city I must not stay around any part too long. So, as it was almost “a small morning hour,” Nina Adams, a widow, was sitting up; for Virginia, a High School girl, was still out; and, around two-thirty, was brought back in a fast car; two youths actually dumping an unconscious form on Nina’s front porch, and dashing madly away. But Nina Adams saw it; and, calling for aid in carrying Virginia indoors, put in a frantic call for old Doc Wilkins, an old, long-ago school pal, who found Nina frantic from not knowing Virginia’s condition, nor why that pair of youths shot madly away without calling anybody. But it only took Doctor Wilkins an instant to find out what was wrong; and Nina, noting his tight lips and growing scowl was in an agony of doubt.

“What is it, Tom? Quick!! I’m almost crazy!!”

Dr. Wilkins, standing by Virginia’s couch, said, slowly:—

“It’s nothing to worry about, Nina. Virginia will pull through all right, by morning.”

But that didn’t satisfy Nina Adams, not for an instant, and Dr. Wilkins, knowing that ironclad spirit of school days which would stand for no obstructions in its path, saw that a “blow-up” was coming; but, through a kindly thought for this woman’s comfort, did not say what his diagnosis was, until Nina, now actually livid with worry, said:—

“Tom Wilkins! Doctor Wilkins, if you wish,—I claim a natural right to know why my child is unconscious! And you, a physician, cannot, by law, withhold such information!!”

But Wilkins, trying to find a way out of a most unhappy condition of affairs, said:—

“Now, Nina, you know I wouldn’t hold anything from you if Virginia was critically ill, but that is not so. If you’ll only wait until morning you’ll find that I am right.”

But this only built obstruction upon obstruction to Nina’s strong will, until Dr. Wilkins, noticing coming total prostration, had to say:—

“Nina, Virginia is drunk; horribly drunk.”

“Drunk!!” Widow Adams had to grab wildly at a chair, sinking into it; at first as limp as a rag, but instantly springing up, blood surging to a throbbing brow. “Drunk! Drunk!! My baby drunk!! Tom, I thank you for trying to ward off this shock; but I’ll say right now, with my hand on high, that I am going to start a rumpus about this atrocity that will rock Branton Hills to its foundations! Who got this young school-girl drunk? I know that Virginia wouldn’t drink that stuff willingly. How could it occur? I pay through taxation for a patrolman in this district; in fact in all districts of this city. What is a patrolman for, if not to watch for just such abominations as this, pray?”

Dr. Wilkins didn’t say, though probably thinking of a rumor that had run around town for a month or two. At this point Virginia, partly conscious, was murmuring:—

“Oh, Norman! Don’t!! I can’t drink it! Oh! I’m so sick!!”

This brought forth all of Nina Adams’ fury instantly.

“Aha! Aha! Norman! So that’s it! That’s Norman Antor, that low-down, good-for-nothing night-owl! Son of our big Councilman Antor. So!! It’s ‘Norman! I can’t drink it’! Tom Wilkins, this thing is going to court!!”

*﻿*﻿*﻿*

About noon of that day, our good doctor, walking sadly along, ran across Mayor Gadsby, in front of City Hall; and did His Honor “burn” at such an abomination?

“What? High School boys forcing young girls to drink? And right in our glorious Branton Hills? Oh, but, Doc! This can’t pass without a trial!”

“That’s all right, John; but a thorn sticks out, right in plain sight.”

“Thorn? Thorn? What kind of a thorn?” and our Mayor was flushing hard, as no kind of wild thoughts would point to any kind of thorns.

“That thorn,” said Wilkins, “is young Norman Antor; son of——”

“Not of Councilman Antor?”

“I am sorry to say that it is so,” and Wilkins told of Virginia’s half-conscious murmurings. “And Nina wants to know why, with a patrolman in all parts of town, it isn’t known that all this drinking is going on. I didn’t say what I thought, but you know that a patrolman don’t go into dancing pavilions and night clubs until conditions sanction it.”

“Who is supplying this liquor?”
